### ISSUE TITLE
Salon No. 7: How to Receive Data from a Remote System?

### ISSUE THREAD

**Issue by jyhi** [UICHCC/HCC-Lectures#6]
# This Salon

- **Name:** How to Receive Data from a Remote System?
- **Speaker:** Michael Long (CST Y3)

# Checklist

**The issue should not be closed before all the following is checked.**

## Before Salon Day

- [x] Send Goliath an email for record
- [x] Book a room: T8-305
- [x] Prepare a flyer
- [x] Prepare a live streaming platform: **Bilibili**
  - [x] Streaming address: https://live.bilibili.com/807816
- [x] Publicity of salon information

## On Salon Day

- [x] Setup white board for outdoor notice
  - [x] Print the flyer and pin it onto the white board
- [x] Setup computer for streaming
- [x] Setup camera
- [x] Setup OBS Studio (recording, scene, etc)
- [x] Setup live streaming (Bilibili)

## After Salon

- [x] Upload materials to this repository
- [x] Upload recording to somewhere: https://www.youtube.com/watch?v=jlISQF6bBoc

**Comment by ecwu** [comment]
Website Updated

**Comment by jyhi** [comment]
> Website Updated

@ecwu  This should also be added to the issue template. Could you please check if 82ee0d0 has any problem?
